[package]
name = "splits"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = { version = "0.8.4", default-features = false }
rusqlite = { version = "0.37.0", default-features = false }
tower-http = { version = "0.6.6", default-features = false, features = ["fs"] }
utoipa = { version = "5.4.0", default-features = false }
utoipa-axum = { version = "0.2.0", default-features = false }
